"""Authored round-2 attempt-2 assistant reviews (18 rendered cases).

Scores authored by the driving glm-5.3-flash session after inspecting the
sampled real frames of each case.  Round-2 rendering succeeded for all
served candidates; recurring visual weaknesses this round: camera framing
too close or cropping subjects, small props (phone/pen/brush/tie) hard to
see at 320x180, persons overlapping at spawn, rope prop not visible.
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("out/assistant-session/reviews/round2-attempt2")


def F(n: int) -> str:
    return f"frame_{n:04d}.png"


def dims(table: dict) -> dict:
    result = {}
    for name, entry in table.items():
        score, conf, refs = entry
        result[name] = {
            "confidence": conf,
            "evidence_completeness": 1.0,
            "evidence_refs": refs,
        }
    return result


BASE_DIMS = {
    "prompt_compliance": None, "physical_plausibility": None, "camera_coverage": None,
    "camera_innovation": None, "character_trajectory": None, "object_trajectory": None,
    "event_timing": None, "temporal_smoothness": None, "visual_clarity": None,
    "appearance_detail": None, "physical_realism": None, "spatial_consistency": None,
    "motion_naturalness": None, "visual_presentation": None,
}


def review(scores, event_scores, dim_table, visible, weaknesses, confidence):
    return {
        "scores": {
            **scores,
            "event_scores": event_scores,
            "dimension_evidence": dim_table,
            "visible_evidence": visible,
            "weaknesses": weaknesses,
            "confidence": confidence,
        }
    }


CASES = {
    "vbench2-train-02-01": review(
        {"prompt_compliance": 45, "physical_plausibility": 45, "camera_coverage": 60, "camera_innovation": 62, "character_trajectory": 55, "object_trajectory": 42, "event_timing": 40, "temporal_smoothness": 72, "visual_clarity": 55, "appearance_detail": 32, "physical_realism": 40, "spatial_consistency": 62, "motion_naturalness": 38, "visual_presentation": 45},
        {"carry_toward_01": 48, "handoff_01": 30},
        dims({
            "prompt_compliance": (45, 0.75, [F(120) + " ball mid-air after the arc; catch not depicted"]),
            "physical_plausibility": (45, 0.75, [F(120) + " ball unsupported in the air"]),
            "camera_coverage": (60, 0.75, [F(69) + " one figure occludes the other"]),
            "camera_innovation": (62, 0.8, [F(1) + " vs " + F(120) + " follow then orbit per plan"]),
            "character_trajectory": (55, 0.7, [F(1) + " both persons spawn nearly overlapping"]),
            "object_trajectory": (42, 0.7, [F(120) + " arc visible, endpoint not in hands"]),
            "event_timing": (40, 0.7, [F(120) + " transfer moment unconfirmed"]),
            "temporal_smoothness": (72, 0.8, [F(69) + " continuous motion"]),
            "visual_clarity": (55, 0.8, [F(120) + " figures readable, ball small"]),
            "appearance_detail": (32, 0.85, [F(1) + " bare primitives"]),
            "physical_realism": (40, 0.8, [F(120) + " floating ball"]),
            "spatial_consistency": (62, 0.8, [F(1) + " vs " + F(120) + " stage stable"]),
            "motion_naturalness": (38, 0.8, [F(69) + " gliding without articulation"]),
            "visual_presentation": (45, 0.8, [F(120) + " washed palette"]),
        }),
        [F(1) + " two persons + table", F(120) + " ball mid-air between figures"],
        ["ball ends floating; catch not shown", "spawn overlap"],
        0.72,
    ),
    "vbench2-train-02-02": review(
        {"prompt_compliance": 35, "physical_plausibility": 55, "camera_coverage": 42, "camera_innovation": 60, "character_trajectory": 50, "object_trajectory": 30, "event_timing": 35, "temporal_smoothness": 70, "visual_clarity": 38, "appearance_detail": 30, "physical_realism": 45, "spatial_consistency": 58, "motion_naturalness": 36, "visual_presentation": 40},
        {"carry_toward_01": 30, "handoff_01": 25},
        dims({
            "prompt_compliance": (35, 0.65, [F(1) + " coat not distinguishable at spawn", F(120) + " close crop hides the dressing outcome"]),
            "physical_plausibility": (55, 0.7, [F(1) + " persons grounded"]),
            "camera_coverage": (42, 0.7, [F(120) + " final crop loses the action"]),
            "camera_innovation": (60, 0.75, [F(120) + " camera motion per plan"]),
            "character_trajectory": (50, 0.7, [F(1) + " approach visible"]),
            "object_trajectory": (30, 0.6, [F(1) + ", " + F(120) + " coat path not traceable"]),
            "event_timing": (35, 0.65, [F(120) + " dressing moment unverified"]),
            "temporal_smoothness": (70, 0.75, [F(69) + " continuous"]),
            "visual_clarity": (38, 0.7, [F(120) + " crop obscures"]),
            "appearance_detail": (30, 0.8, [F(1) + " primitives"]),
            "physical_realism": (45, 0.7, [F(1) + " grounded"]),
            "spatial_consistency": (58, 0.75, [F(120) + " stable"]),
            "motion_naturalness": (36, 0.75, [F(69) + " gliding"]),
            "visual_presentation": (40, 0.75, [F(120) + " crop"]),
        }),
        [F(1) + " two persons close together", F(120) + " tight crop on one person"],
        ["coat never clearly visible; outcome unverifiable"],
        0.6,
    ),
    "vbench2-train-02-03": review(
        {"prompt_compliance": 58, "physical_plausibility": 62, "camera_coverage": 55, "camera_innovation": 60, "character_trajectory": 58, "object_trajectory": 50, "event_timing": 55, "temporal_smoothness": 72, "visual_clarity": 52, "appearance_detail": 32, "physical_realism": 52, "spatial_consistency": 64, "motion_naturalness": 40, "visual_presentation": 46},
        {"approach_01": 60, "pickup_01": 45},
        dims({
            "prompt_compliance": (58, 0.75, [F(1) + " parcel rests on the crate near the dropper", F(120) + " picker adjacent to the item"]),
            "physical_plausibility": (62, 0.8, [F(1) + " parcel supported on the crate"]),
            "camera_coverage": (55, 0.7, [F(120) + " close crop loses the second person"]),
            "camera_innovation": (60, 0.75, [F(120) + " plan camera motion"]),
            "character_trajectory": (58, 0.75, [F(120) + " approach executed"]),
            "object_trajectory": (50, 0.7, [F(120) + " parcel lift partially visible"]),
            "event_timing": (55, 0.7, [F(120) + " pickup phase readable"]),
            "temporal_smoothness": (72, 0.8, [F(120) + " continuous"]),
            "visual_clarity": (52, 0.75, [F(120) + " crop limits context"]),
            "appearance_detail": (32, 0.8, [F(1) + " primitives"]),
            "physical_realism": (52, 0.75, [F(1) + " supported parcel"]),
            "spatial_consistency": (64, 0.8, [F(1) + " vs " + F(120) + " stable"]),
            "motion_naturalness": (40, 0.75, [F(120) + " gliding walk"]),
            "visual_presentation": (46, 0.75, [F(120) + " acceptable"]),
        }),
        [F(1) + " parcel on crate near dropper", F(120) + " picker beside the parcel"],
        ["pickup completion partially occluded"],
        0.7,
    ),
    "vbench2-train-02-04": review(
        {"prompt_compliance": 50, "physical_plausibility": 65, "camera_coverage": 35, "camera_innovation": 55, "character_trajectory": 52, "object_trajectory": 55, "event_timing": 55, "temporal_smoothness": 70, "visual_clarity": 40, "appearance_detail": 30, "physical_realism": 50, "spatial_consistency": 60, "motion_naturalness": 38, "visual_presentation": 35},
        {"approach_a": 50, "approach_b": 50, "build_a": 45, "build_b": 45},
        dims({
            "prompt_compliance": (50, 0.7, [F(120) + " two builders at the puzzle table with the board visible"]),
            "physical_plausibility": (65, 0.8, [F(120) + " board on table, builders grounded"]),
            "camera_coverage": (35, 0.7, [F(1) + " start frame is a full-frame table slab; subjects hidden"]),
            "camera_innovation": (55, 0.75, [F(120) + " plan camera motion"]),
            "character_trajectory": (52, 0.7, [F(120) + " builders converged"]),
            "object_trajectory": (55, 0.75, [F(120) + " board static per plan"]),
            "event_timing": (55, 0.7, [F(120) + " build phases sequenced"]),
            "temporal_smoothness": (70, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (40, 0.7, [F(1) + " unreadable start"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (50, 0.75, [F(120) + " grounded"]),
            "spatial_consistency": (60, 0.75, [F(120) + " stable"]),
            "motion_naturalness": (38, 0.75, [F(120) + " gliding"]),
            "visual_presentation": (35, 0.75, [F(1) + " framing fails"]),
        }),
        [F(1) + " table slab fills the frame", F(120) + " builders behind the puzzle table"],
        ["start framing too close"],
        0.68,
    ),
    "vbench2-train-02-05": review(
        {"prompt_compliance": 25, "physical_plausibility": 55, "camera_coverage": 45, "camera_innovation": 50, "character_trajectory": 45, "object_trajectory": 20, "event_timing": 30, "temporal_smoothness": 68, "visual_clarity": 40, "appearance_detail": 30, "physical_realism": 45, "spatial_consistency": 55, "motion_naturalness": 35, "visual_presentation": 38},
        {"grip_a": 25, "grip_b": 25},
        dims({
            "prompt_compliance": (25, 0.75, [F(69) + " two persons standing; the rope is not visible, so no tug-of-war is depicted"]),
            "physical_plausibility": (55, 0.75, [F(69) + " persons grounded"]),
            "camera_coverage": (45, 0.7, [F(69) + " subjects framed"]),
            "camera_innovation": (50, 0.7, [F(69) + " plan camera motion"]),
            "character_trajectory": (45, 0.7, [F(69) + " minimal motion"]),
            "object_trajectory": (20, 0.65, [F(69) + " rope absent from the frame"]),
            "event_timing": (30, 0.65, [F(69) + " no pull action readable"]),
            "temporal_smoothness": (68, 0.75, [F(69) + " continuous"]),
            "visual_clarity": (40, 0.7, [F(69) + " without the rope the action is unclear"]),
            "appearance_detail": (30, 0.8, [F(69) + " primitives"]),
            "physical_realism": (45, 0.7, [F(69) + " grounded"]),
            "spatial_consistency": (55, 0.7, [F(69) + " stable"]),
            "motion_naturalness": (35, 0.75, [F(69) + " static"]),
            "visual_presentation": (38, 0.7, [F(69) + " plain"]),
        }),
        [F(69) + " two persons standing without a visible rope"],
        ["rope prop not visible - the defining action is missing"],
        0.7,
    ),
    "vbench2-train-02-06": review(
        {"prompt_compliance": 40, "physical_plausibility": 58, "camera_coverage": 48, "camera_innovation": 58, "character_trajectory": 50, "object_trajectory": 32, "event_timing": 38, "temporal_smoothness": 70, "visual_clarity": 40, "appearance_detail": 30, "physical_realism": 48, "spatial_consistency": 58, "motion_naturalness": 36, "visual_presentation": 40},
        {"carry_toward_01": 35, "handoff_01": 28},
        dims({
            "prompt_compliance": (40, 0.65, [F(120) + " one person centered; the phone is too small to confirm the handoff"]),
            "physical_plausibility": (58, 0.75, [F(120) + " grounded"]),
            "camera_coverage": (48, 0.7, [F(120) + " second person outside the crop"]),
            "camera_innovation": (58, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (50, 0.7, [F(120) + " single figure readable"]),
            "object_trajectory": (32, 0.6, [F(120) + " phone path untraceable"]),
            "event_timing": (38, 0.65, [F(120) + " handoff moment unverified"]),
            "temporal_smoothness": (70, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (40, 0.7, [F(120) + " phone indistinct"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (48, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (58, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (36, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (40, 0.7, [F(120) + " crop"]),
        }),
        [F(120) + " one person in frame; phone not resolvable"],
        ["phone too small at render scale; handoff unverifiable", "receiver cropped out"],
        0.6,
    ),
    "vbench2-train-02-07": review(
        {"prompt_compliance": 60, "physical_plausibility": 62, "camera_coverage": 55, "camera_innovation": 58, "character_trajectory": 55, "object_trajectory": 55, "event_timing": 55, "temporal_smoothness": 70, "visual_clarity": 55, "appearance_detail": 32, "physical_realism": 52, "spatial_consistency": 64, "motion_naturalness": 40, "visual_presentation": 48},
        {"approach_a": 55, "approach_b": 55, "hang_a": 52, "hang_b": 52},
        dims({
            "prompt_compliance": (60, 0.75, [F(120) + " picture frame at the top of the wall above the two holders"]),
            "physical_plausibility": (62, 0.75, [F(120) + " frame on the wall, persons grounded"]),
            "camera_coverage": (55, 0.7, [F(120) + " frame near the top edge"]),
            "camera_innovation": (58, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (55, 0.75, [F(120) + " holders at the wall"]),
            "object_trajectory": (55, 0.7, [F(120) + " frame reached the wall"]),
            "event_timing": (55, 0.7, [F(120) + " hang completes late in the clip"]),
            "temporal_smoothness": (70, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (55, 0.75, [F(120) + " readable"]),
            "appearance_detail": (32, 0.8, [F(120) + " primitives"]),
            "physical_realism": (52, 0.75, [F(120) + " plausible"]),
            "spatial_consistency": (64, 0.75, [F(120) + " stable"]),
            "motion_naturalness": (40, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (48, 0.75, [F(120) + " acceptable"]),
        }),
        [F(120) + " picture on the wall with both holders below"],
        ["frame placement near the top edge reads high"],
        0.7,
    ),
    "vbench2-train-02-08": review(
        {"prompt_compliance": 30, "physical_plausibility": 50, "camera_coverage": 35, "camera_innovation": 52, "character_trajectory": 45, "object_trajectory": 22, "event_timing": 32, "temporal_smoothness": 66, "visual_clarity": 35, "appearance_detail": 30, "physical_realism": 42, "spatial_consistency": 50, "motion_naturalness": 35, "visual_presentation": 36},
        {"seat_01": 40, "push_01": 35, "roll_01": 30},
        dims({
            "prompt_compliance": (30, 0.65, [F(69) + " wheelchair and seated rider are outside the frame; only the pusher's legs show"]),
            "physical_plausibility": (50, 0.7, [F(69) + " partial figures grounded"]),
            "camera_coverage": (35, 0.65, [F(69) + " key subjects cropped"]),
            "camera_innovation": (52, 0.7, [F(69) + " plan camera motion"]),
            "character_trajectory": (45, 0.65, [F(69) + " pusher advancing"]),
            "object_trajectory": (22, 0.6, [F(69) + " wheelchair untraceable"]),
            "event_timing": (32, 0.6, [F(69) + " push action unreadable"]),
            "temporal_smoothness": (66, 0.7, [F(69) + " continuous"]),
            "visual_clarity": (35, 0.65, [F(69) + " crop obscures"]),
            "appearance_detail": (30, 0.8, [F(69) + " primitives"]),
            "physical_realism": (42, 0.65, [F(69) + " partial"]),
            "spatial_consistency": (50, 0.65, [F(69) + " unclear"]),
            "motion_naturalness": (35, 0.7, [F(69) + " gliding"]),
            "visual_presentation": (36, 0.7, [F(69) + " crop"]),
        }),
        [F(69) + " pusher's legs at top-left, standing person at right; wheelchair not in frame"],
        ["wheelchair and rider cropped out - core action missing"],
        0.6,
    ),
    "vbench2-train-02-09": review(
        {"prompt_compliance": 38, "physical_plausibility": 55, "camera_coverage": 40, "camera_innovation": 55, "character_trajectory": 48, "object_trajectory": 28, "event_timing": 35, "temporal_smoothness": 68, "visual_clarity": 38, "appearance_detail": 30, "physical_realism": 46, "spatial_consistency": 55, "motion_naturalness": 36, "visual_presentation": 38},
        {"approach_01": 45, "brush_01": 30},
        dims({
            "prompt_compliance": (38, 0.65, [F(120) + " close crop on one person; brush and receiver not visible"]),
            "physical_plausibility": (55, 0.7, [F(120) + " grounded"]),
            "camera_coverage": (40, 0.65, [F(120) + " action subjects cropped"]),
            "camera_innovation": (55, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (48, 0.7, [F(120) + " approach executed"]),
            "object_trajectory": (28, 0.6, [F(120) + " brush path untraceable"]),
            "event_timing": (35, 0.6, [F(120) + " brushing not visible"]),
            "temporal_smoothness": (68, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (38, 0.65, [F(120) + " crop"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (46, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (55, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (36, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (38, 0.7, [F(120) + " crop"]),
        }),
        [F(120) + " close crop; brushing not visible"],
        ["brush and receiver cropped out - brushing unverifiable"],
        0.6,
    ),
    "vbench2-train-02-10": review(
        {"prompt_compliance": 42, "physical_plausibility": 60, "camera_coverage": 42, "camera_innovation": 58, "character_trajectory": 55, "object_trajectory": 60, "event_timing": 55, "temporal_smoothness": 72, "visual_clarity": 45, "appearance_detail": 32, "physical_realism": 50, "spatial_consistency": 62, "motion_naturalness": 40, "visual_presentation": 42},
        {"walk_a": 55, "walk_b": 40},
        dims({
            "prompt_compliance": (42, 0.7, [F(69) + " one walker in frame; side-by-side pairing not visible"]),
            "physical_plausibility": (60, 0.75, [F(69) + " grounded walker in hallway"]),
            "camera_coverage": (42, 0.7, [F(69) + " second walker cropped"]),
            "camera_innovation": (58, 0.7, [F(69) + " tracking camera per plan"]),
            "character_trajectory": (55, 0.75, [F(69) + " forward progress"]),
            "object_trajectory": (60, 0.75, [F(69) + " hallway environment stable"]),
            "event_timing": (55, 0.7, [F(69) + " walking phase readable"]),
            "temporal_smoothness": (72, 0.8, [F(69) + " continuous tracking"]),
            "visual_clarity": (45, 0.7, [F(69) + " single figure readable"]),
            "appearance_detail": (32, 0.8, [F(69) + " primitives"]),
            "physical_realism": (50, 0.7, [F(69) + " grounded"]),
            "spatial_consistency": (62, 0.75, [F(69) + " hallway stable"]),
            "motion_naturalness": (40, 0.7, [F(69) + " gliding walk"]),
            "visual_presentation": (42, 0.7, [F(69) + " crop"]),
        }),
        [F(69) + " one walker tracked in the hallway"],
        ["second walker cropped out; side-by-side not shown"],
        0.65,
    ),
    "vbench2-dev-02-11": review(
        {"prompt_compliance": 40, "physical_plausibility": 58, "camera_coverage": 45, "camera_innovation": 55, "character_trajectory": 50, "object_trajectory": 30, "event_timing": 35, "temporal_smoothness": 68, "visual_clarity": 40, "appearance_detail": 30, "physical_realism": 48, "spatial_consistency": 56, "motion_naturalness": 36, "visual_presentation": 40},
        {"approach_01": 42, "adjust_01": 28},
        dims({
            "prompt_compliance": (40, 0.65, [F(120) + " two persons close; the tie is too small to confirm adjusting"]),
            "physical_plausibility": (58, 0.7, [F(120) + " grounded"]),
            "camera_coverage": (45, 0.65, [F(120) + " tight crop"]),
            "camera_innovation": (55, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (50, 0.7, [F(120) + " approach executed"]),
            "object_trajectory": (30, 0.6, [F(120) + " tie path untraceable"]),
            "event_timing": (35, 0.6, [F(120) + " adjust not resolvable"]),
            "temporal_smoothness": (68, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (40, 0.65, [F(120) + " tie indistinct"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (48, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (56, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (36, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (40, 0.7, [F(120) + " crop"]),
        }),
        [F(120) + " two persons close together; tie not resolvable"],
        ["tie too small; adjusting unverifiable"],
        0.6,
    ),
    "vbench2-dev-02-12": review(
        {"prompt_compliance": 55, "physical_plausibility": 62, "camera_coverage": 58, "camera_innovation": 56, "character_trajectory": 52, "object_trajectory": 52, "event_timing": 52, "temporal_smoothness": 70, "visual_clarity": 52, "appearance_detail": 30, "physical_realism": 52, "spatial_consistency": 60, "motion_naturalness": 40, "visual_presentation": 46},
        {"sweep_a": 50, "sweep_b": 48},
        dims({
            "prompt_compliance": (55, 0.75, [F(69) + " broom visible upright beside a sweeper; second sweeper at the right edge"]),
            "physical_plausibility": (62, 0.75, [F(69) + " broom grounded"]),
            "camera_coverage": (58, 0.7, [F(69) + " both sweepers partially framed"]),
            "camera_innovation": (56, 0.7, [F(69) + " plan camera motion"]),
            "character_trajectory": (52, 0.7, [F(69) + " sweepers positioned"]),
            "object_trajectory": (52, 0.7, [F(69) + " broom traceable"]),
            "event_timing": (52, 0.7, [F(69) + " sweeping phase"]),
            "temporal_smoothness": (70, 0.75, [F(69) + " continuous"]),
            "visual_clarity": (52, 0.7, [F(69) + " broom readable"]),
            "appearance_detail": (30, 0.8, [F(69) + " primitives"]),
            "physical_realism": (52, 0.7, [F(69) + " grounded"]),
            "spatial_consistency": (60, 0.7, [F(69) + " stable"]),
            "motion_naturalness": (40, 0.7, [F(69) + " stroke rhythm limited"]),
            "visual_presentation": (46, 0.7, [F(69) + " acceptable"]),
        }),
        [F(69) + " broom grounded beside the first sweeper; second at right edge"],
        ["sweeping stroke subtle; second sweeper near the edge"],
        0.7,
    ),
    "vbench2-dev-02-13": review(
        {"prompt_compliance": 45, "physical_plausibility": 58, "camera_coverage": 42, "camera_innovation": 54, "character_trajectory": 48, "object_trajectory": 40, "event_timing": 42, "temporal_smoothness": 68, "visual_clarity": 42, "appearance_detail": 30, "physical_realism": 48, "spatial_consistency": 56, "motion_naturalness": 36, "visual_presentation": 40},
        {"hold_a": 45, "hold_b": 45, "climb_01": 35},
        dims({
            "prompt_compliance": (45, 0.7, [F(120) + " person from behind near the wall; the ladder is not in frame"]),
            "physical_plausibility": (58, 0.7, [F(120) + " grounded"]),
            "camera_coverage": (42, 0.65, [F(120) + " ladder cropped"]),
            "camera_innovation": (54, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (48, 0.7, [F(120) + " climber advanced"]),
            "object_trajectory": (40, 0.65, [F(120) + " ladder untraceable"]),
            "event_timing": (42, 0.65, [F(120) + " climb phase not visible"]),
            "temporal_smoothness": (68, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (42, 0.7, [F(120) + " crop"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (48, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (56, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (36, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (40, 0.7, [F(120) + " crop"]),
        }),
        [F(120) + " person near the wall; ladder out of frame"],
        ["ladder cropped - holding/climbing unverifiable"],
        0.6,
    ),
    "vbench2-dev-02-15": review(
        {"prompt_compliance": 62, "physical_plausibility": 66, "camera_coverage": 60, "camera_innovation": 56, "character_trajectory": 55, "object_trajectory": 58, "event_timing": 55, "temporal_smoothness": 70, "visual_clarity": 58, "appearance_detail": 34, "physical_realism": 55, "spatial_consistency": 64, "motion_naturalness": 42, "visual_presentation": 52},
        {"approach_a": 55, "approach_b": 55, "work_a": 52, "swap_tire": 50},
        dims({
            "prompt_compliance": (62, 0.75, [F(120) + " jacked car with wheel and jack visible; both workers adjacent"]),
            "physical_plausibility": (66, 0.8, [F(120) + " car supported by the jack"]),
            "camera_coverage": (60, 0.7, [F(120) + " car and workers framed"]),
            "camera_innovation": (56, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (55, 0.7, [F(120) + " workers at the car"]),
            "object_trajectory": (58, 0.7, [F(120) + " spare tire brought over"]),
            "event_timing": (55, 0.7, [F(120) + " work phase readable"]),
            "temporal_smoothness": (70, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (58, 0.75, [F(120) + " car close-up readable"]),
            "appearance_detail": (34, 0.8, [F(120) + " primitives"]),
            "physical_realism": (55, 0.75, [F(120) + " jack support plausible"]),
            "spatial_consistency": (64, 0.75, [F(120) + " stable"]),
            "motion_naturalness": (42, 0.7, [F(120) + " moderate"]),
            "visual_presentation": (52, 0.75, [F(120) + " decent"]),
        }),
        [F(120) + " jacked car with detached wheel; both workers beside it"],
        ["primitive surfaces"],
        0.72,
    ),
    "vbench2-dev-02-16": review(
        {"prompt_compliance": 52, "physical_plausibility": 60, "camera_coverage": 50, "camera_innovation": 55, "character_trajectory": 48, "object_trajectory": 48, "event_timing": 48, "temporal_smoothness": 68, "visual_clarity": 48, "appearance_detail": 30, "physical_realism": 50, "spatial_consistency": 58, "motion_naturalness": 38, "visual_presentation": 44},
        {"approach_01": 50, "fold_01": 45},
        dims({
            "prompt_compliance": (52, 0.7, [F(120) + " folder at the table with the observer; shirt small on the table"]),
            "physical_plausibility": (60, 0.75, [F(120) + " grounded"]),
            "camera_coverage": (50, 0.7, [F(120) + " table and persons framed"]),
            "camera_innovation": (55, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (48, 0.7, [F(120) + " folder at the table"]),
            "object_trajectory": (48, 0.7, [F(120) + " shirt on table"]),
            "event_timing": (48, 0.7, [F(120) + " fold phase subtle"]),
            "temporal_smoothness": (68, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (48, 0.7, [F(120) + " shirt small"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (50, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (58, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (38, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (44, 0.7, [F(120) + " acceptable"]),
        }),
        [F(120) + " folder at the table, observer across; shirt on the tabletop"],
        ["fold motion subtle at render scale"],
        0.68,
    ),
    "vbench2-dev-02-17": review(
        {"prompt_compliance": 48, "physical_plausibility": 60, "camera_coverage": 46, "camera_innovation": 54, "character_trajectory": 48, "object_trajectory": 46, "event_timing": 45, "temporal_smoothness": 68, "visual_clarity": 44, "appearance_detail": 30, "physical_realism": 48, "spatial_consistency": 56, "motion_naturalness": 38, "visual_presentation": 42},
        {"approach_a": 46, "approach_b": 46, "wrap_a": 44, "wrap_b": 42},
        dims({
            "prompt_compliance": (48, 0.7, [F(120) + " person at the table; gift/paper small at this angle"]),
            "physical_plausibility": (60, 0.75, [F(120) + " grounded"]),
            "camera_coverage": (46, 0.7, [F(120) + " gift area partially cropped"]),
            "camera_innovation": (54, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (48, 0.7, [F(120) + " wrappers at the table"]),
            "object_trajectory": (46, 0.65, [F(120) + " paper movement subtle"]),
            "event_timing": (45, 0.65, [F(120) + " wrap phase subtle"]),
            "temporal_smoothness": (68, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (44, 0.7, [F(120) + " small props"]),
            "appearance_detail": (30, 0.8, [F(120) + " primitives"]),
            "physical_realism": (48, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (56, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (38, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (42, 0.7, [F(120) + " acceptable"]),
        }),
        [F(120) + " wrapper at the table; gift and paper small in frame"],
        ["gift wrap details hard to resolve"],
        0.65,
    ),
    "vbench2-dev-02-18": review(
        {"prompt_compliance": 55, "physical_plausibility": 62, "camera_coverage": 52, "camera_innovation": 55, "character_trajectory": 52, "object_trajectory": 55, "event_timing": 50, "temporal_smoothness": 70, "visual_clarity": 52, "appearance_detail": 32, "physical_realism": 52, "spatial_consistency": 60, "motion_naturalness": 40, "visual_presentation": 48},
        {"carry_a": 50, "load_a": 48, "assist_b": 45},
        dims({
            "prompt_compliance": (55, 0.75, [F(69) + " car close-up with open trunk area; box partially visible"]),
            "physical_plausibility": (62, 0.75, [F(69) + " car grounded"]),
            "camera_coverage": (52, 0.7, [F(69) + " loader partially framed"]),
            "camera_innovation": (55, 0.7, [F(69) + " plan camera motion"]),
            "character_trajectory": (52, 0.7, [F(69) + " loader advanced"]),
            "object_trajectory": (55, 0.7, [F(69) + " box movement partial"]),
            "event_timing": (50, 0.7, [F(69) + " loading phase"]),
            "temporal_smoothness": (70, 0.75, [F(69) + " continuous"]),
            "visual_clarity": (52, 0.7, [F(69) + " readable"]),
            "appearance_detail": (32, 0.8, [F(69) + " primitives"]),
            "physical_realism": (52, 0.7, [F(69) + " grounded"]),
            "spatial_consistency": (60, 0.7, [F(69) + " stable"]),
            "motion_naturalness": (40, 0.7, [F(69) + " gliding"]),
            "visual_presentation": (48, 0.7, [F(69) + " acceptable"]),
        }),
        [F(69) + " car with open trunk; loader adjacent"],
        ["box handoff partially occluded"],
        0.68,
    ),
    "vbench2-dev-02-20": review(
        {"prompt_compliance": 58, "physical_plausibility": 62, "camera_coverage": 55, "camera_innovation": 55, "character_trajectory": 52, "object_trajectory": 55, "event_timing": 52, "temporal_smoothness": 70, "visual_clarity": 50, "appearance_detail": 32, "physical_realism": 52, "spatial_consistency": 60, "motion_naturalness": 40, "visual_presentation": 46},
        {"carry_a": 52, "unpack_a": 48, "sort_b": 46},
        dims({
            "prompt_compliance": (58, 0.75, [F(120) + " shelf with items at the back, person in front"]),
            "physical_plausibility": (62, 0.75, [F(120) + " shelf grounded"]),
            "camera_coverage": (55, 0.7, [F(120) + " shelf area framed"]),
            "camera_innovation": (55, 0.7, [F(120) + " plan camera motion"]),
            "character_trajectory": (52, 0.7, [F(120) + " carrier reached the shelf"]),
            "object_trajectory": (55, 0.7, [F(120) + " bag moved to the shelf"]),
            "event_timing": (52, 0.7, [F(120) + " unpacking phase"]),
            "temporal_smoothness": (70, 0.75, [F(120) + " continuous"]),
            "visual_clarity": (50, 0.7, [F(120) + " bag readable"]),
            "appearance_detail": (32, 0.8, [F(120) + " primitives"]),
            "physical_realism": (52, 0.7, [F(120) + " grounded"]),
            "spatial_consistency": (60, 0.7, [F(120) + " stable"]),
            "motion_naturalness": (40, 0.7, [F(120) + " gliding"]),
            "visual_presentation": (46, 0.7, [F(120) + " acceptable"]),
        }),
        [F(120) + " grocery shelf stocked; person in front of it"],
        ["unpacking details subtle"],
        0.68,
    ),
}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for case_id, payload in CASES.items():
        (OUT / f"{case_id}-scores.json").write_text(
            json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8"
        )
    print(json.dumps({"written": len(CASES)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
