"""Authored round-1 attempt-2 assistant reviews (20 rendered cases).

Scores authored by the driving glm-5.3-flash session after inspecting
frames 0001/0069/0120 (and 0035 where relevant) of each real proxy.mp4.
Attempt-2 evidence notes: stage alignment grounded the previously hovering
subjects (vase/burj/forbidden city/laptop/watch), the static-camera and
small-radius geometry crashes are gone, zoom-in/tilt-up framing improved;
remaining weaknesses: orbit mid-phase framing still drops the subject,
table assembly still mis-proportioned, near-white palette.
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("out/assistant-session/reviews/round1-attempt2")


def F(n: int) -> str:
    return f"frame_{n:04d}.png"


def dims(table: dict) -> dict:
    return {
        name: {"confidence": conf, "evidence_completeness": 1.0, "evidence_refs": refs}
        for name, (score, conf, refs) in table.items()
    }


NO_CHARACTER = "no character is present in the prompt or frames"

REVIEW_CASES: dict[str, dict] = {
    "vbench2-train-01-01": {
        "scores": {"prompt_compliance": 72, "physical_plausibility": 82, "camera_coverage": 52, "camera_innovation": 78, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 70, "temporal_smoothness": 85, "visual_clarity": 50, "appearance_detail": 40, "physical_realism": 58, "spatial_consistency": 80, "motion_naturalness": 70, "visual_presentation": 48},
        "event_scores": {"observe_01": 72},
        "dimension_evidence": dims({
            "prompt_compliance": (72, 0.8, [F(120) + " garden fully framed: mound, tree crowns, platform"]),
            "physical_plausibility": (82, 0.85, [F(120) + " garden grounded on the aligned stage"]),
            "camera_coverage": (52, 0.8, [F(1) + " start over-cropped", F(120) + " end framed"]),
            "camera_innovation": (78, 0.9, [F(1) + " vs " + F(120) + " dolly-out per cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.85, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (85, 0.9, [F(69) + " continuous pull-back"]),
            "visual_clarity": (50, 0.85, [F(1) + " unreadable start crop"]),
            "appearance_detail": (40, 0.85, [F(120) + " bare primitives, flat shading"]),
            "physical_realism": (58, 0.85, [F(120) + " grounded, weak shadows"]),
            "spatial_consistency": (80, 0.85, [F(1) + " vs " + F(120) + " stable layout"]),
            "motion_naturalness": (70, 0.8, [F(69) + " steady dolly"]),
            "visual_presentation": (48, 0.8, [F(120) + " good end frame, monotone palette"]),
        }),
        "visible_evidence": [F(1) + " mound overfills frame", F(120) + " garden diorama fully framed"],
        "weaknesses": ["start framing too close", "washed-out palette"],
        "confidence": 0.78,
    },
    "vbench2-train-01-02": {
        "scores": {"prompt_compliance": 60, "physical_plausibility": 80, "camera_coverage": 40, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 72, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 42, "appearance_detail": 38, "physical_realism": 56, "spatial_consistency": 76, "motion_naturalness": 70, "visual_presentation": 42},
        "event_scores": {"observe_01": 55},
        "dimension_evidence": dims({
            "prompt_compliance": (60, 0.8, [F(120) + " garden visible after orbit, top cropped"]),
            "physical_plausibility": (80, 0.85, [F(120) + " grounded on stage"]),
            "camera_coverage": (40, 0.85, [F(69) + " subject at the right edge mid-orbit", F(120) + " end crop cuts the crown"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(69) + " vs " + F(120) + " clockwise orbit executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (72, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous arc"]),
            "visual_clarity": (42, 0.85, [F(69) + " subject marginal at edge"]),
            "appearance_detail": (38, 0.8, [F(120) + " primitive shapes"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (76, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth arc"]),
            "visual_presentation": (42, 0.8, [F(120) + " end crop imperfect"]),
        }),
        "visible_evidence": [F(69) + " garden at the right edge mid-orbit", F(120) + " orbit completes with partial crop"],
        "weaknesses": ["orbit mid-phase framing still drops the subject", "end frame crops the tree crowns"],
        "confidence": 0.75,
    },
    "vbench2-train-01-03": {
        "scores": {"prompt_compliance": 78, "physical_plausibility": 82, "camera_coverage": 82, "camera_innovation": 76, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 72, "temporal_smoothness": 84, "visual_clarity": 75, "appearance_detail": 42, "physical_realism": 58, "spatial_consistency": 82, "motion_naturalness": 70, "visual_presentation": 62},
        "event_scores": {"observe_01": 75},
        "dimension_evidence": dims({
            "prompt_compliance": (78, 0.85, [F(1) + " stepped pyramid centered", F(120) + " courses readable after tilt"]),
            "physical_plausibility": (82, 0.85, [F(120) + " pyramid grounded on the aligned stage"]),
            "camera_coverage": (82, 0.85, [F(1) + ", " + F(120) + " subject framed"]),
            "camera_innovation": (76, 0.9, [F(1) + " vs " + F(120) + " tilt-down descend executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous descend"]),
            "visual_clarity": (75, 0.85, [F(120) + " stepped courses readable"]),
            "appearance_detail": (42, 0.8, [F(120) + " flat facets"]),
            "physical_realism": (58, 0.8, [F(120) + " grounded contact"]),
            "spatial_consistency": (82, 0.85, [F(1) + " vs " + F(120) + " stage stable"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth descend"]),
            "visual_presentation": (62, 0.8, [F(120) + " balanced close crop"]),
        }),
        "visible_evidence": [F(1) + " pyramid well framed", F(120) + " tilt-down ends readable"],
        "weaknesses": ["untextured surfaces"],
        "confidence": 0.8,
    },
    "vbench2-train-01-04": {
        "scores": {"prompt_compliance": 68, "physical_plausibility": 80, "camera_coverage": 62, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 82, "visual_clarity": 62, "appearance_detail": 38, "physical_realism": 56, "spatial_consistency": 76, "motion_naturalness": 68, "visual_presentation": 55},
        "event_scores": {"observe_01": 66},
        "dimension_evidence": dims({
            "prompt_compliance": (68, 0.85, [F(120) + " full cone silhouette readable after zoom-in (improved over slope-only crop)"]),
            "physical_plausibility": (80, 0.85, [F(120) + " grounded cone"]),
            "camera_coverage": (62, 0.85, [F(120) + " subject still fully framed at zoom end"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " dolly-in executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (82, 0.85, [F(69) + " continuous push"]),
            "visual_clarity": (62, 0.85, [F(120) + " silhouette readable"]),
            "appearance_detail": (38, 0.8, [F(120) + " primitive cone, faint snow cap"]),
            "physical_realism": (56, 0.8, [F(120) + " plausible mass"]),
            "spatial_consistency": (76, 0.85, [F(120) + " stage stable"]),
            "motion_naturalness": (68, 0.8, [F(69) + " steady dolly"]),
            "visual_presentation": (55, 0.8, [F(120) + " acceptable end framing"]),
        }),
        "visible_evidence": [F(120) + " zoom-in keeps the full cone silhouette in frame"],
        "weaknesses": ["flat lighting", "minimal surface detail"],
        "confidence": 0.78,
    },
    "vbench2-train-01-05": {
        "scores": {"prompt_compliance": 78, "physical_plausibility": 82, "camera_coverage": 80, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 72, "temporal_smoothness": 84, "visual_clarity": 76, "appearance_detail": 40, "physical_realism": 56, "spatial_consistency": 80, "motion_naturalness": 70, "visual_presentation": 62},
        "event_scores": {"observe_01": 75},
        "dimension_evidence": dims({
            "prompt_compliance": (78, 0.85, [F(120) + " mountain fully framed after pan-left"]),
            "physical_plausibility": (82, 0.85, [F(120) + " grounded cone"]),
            "camera_coverage": (80, 0.85, [F(120) + " subject fully visible"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (76, 0.85, [F(120) + " silhouette readable"]),
            "appearance_detail": (40, 0.8, [F(120) + " untextured surfaces"]),
            "physical_realism": (56, 0.8, [F(120) + " plausible mass"]),
            "spatial_consistency": (80, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (62, 0.8, [F(120) + " balanced composition"]),
        }),
        "visible_evidence": [F(120) + " pan-left ends with the mountain fully framed"],
        "weaknesses": ["flat lighting"],
        "confidence": 0.8,
    },
    "vbench2-train-01-06": {
        "scores": {"prompt_compliance": 66, "physical_plausibility": 78, "camera_coverage": 76, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 82, "visual_clarity": 66, "appearance_detail": 40, "physical_realism": 54, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 56},
        "event_scores": {"observe_01": 66},
        "dimension_evidence": dims({
            "prompt_compliance": (66, 0.8, [F(120) + " lagoon ring and palm revealed by tilt-up"]),
            "physical_plausibility": (78, 0.85, [F(120) + " lagoon grounded on the aligned stage"]),
            "camera_coverage": (76, 0.85, [F(120) + " lagoon framed"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " camera rises per tilt-up cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (82, 0.85, [F(69) + " continuous rise"]),
            "visual_clarity": (66, 0.85, [F(120) + " ring readable, water flat"]),
            "appearance_detail": (40, 0.8, [F(120) + " no ripples or translucency"]),
            "physical_realism": (54, 0.8, [F(120) + " solid opaque water disc"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth rise"]),
            "visual_presentation": (56, 0.8, [F(120) + " muted palette"]),
        }),
        "visible_evidence": [F(120) + " tilt-up reveals the lagoon disc and palm"],
        "weaknesses": ["water renders opaque and ripple-free"],
        "confidence": 0.75,
    },
    "vbench2-train-01-07": {
        "scores": {"prompt_compliance": 74, "physical_plausibility": 80, "camera_coverage": 82, "camera_innovation": 60, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 72, "temporal_smoothness": 78, "visual_clarity": 74, "appearance_detail": 40, "physical_realism": 56, "spatial_consistency": 80, "motion_naturalness": 68, "visual_presentation": 62},
        "event_scores": {"observe_01": 74},
        "dimension_evidence": dims({
            "prompt_compliance": (74, 0.85, [F(120) + " lagoon with shore ring and palm, static framing"]),
            "physical_plausibility": (80, 0.85, [F(120) + " lagoon grounded on the aligned stage"]),
            "camera_coverage": (82, 0.85, [F(1) + ", " + F(120) + " fixed camera keeps the subject framed"]),
            "camera_innovation": (60, 0.85, [F(1) + " vs " + F(120) + " static per cue; no motion requested or executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (78, 0.85, [F(120) + " no motion, no artifacts"]),
            "visual_clarity": (74, 0.85, [F(120) + " readable three-quarter view"]),
            "appearance_detail": (40, 0.8, [F(120) + " flat water disc, primitive palm"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (80, 0.85, [F(1) + " vs " + F(120) + " identical framing per static cue"]),
            "motion_naturalness": (68, 0.8, [F(120) + " no motion to judge"]),
            "visual_presentation": (62, 0.8, [F(120) + " stable composition"]),
        }),
        "visible_evidence": [F(120) + " static shot holds the lagoon in a stable three-quarter view"],
        "weaknesses": ["static cue correctly yields no motion; presentation remains primitive"],
        "confidence": 0.8,
    },
    "vbench2-train-01-08": {
        "scores": {"prompt_compliance": 42, "physical_plausibility": 24, "camera_coverage": 76, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 40, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 58, "appearance_detail": 35, "physical_realism": 26, "spatial_consistency": 58, "motion_naturalness": 66, "visual_presentation": 38},
        "event_scores": {"observe_01": 50},
        "dimension_evidence": dims({
            "prompt_compliance": (42, 0.85, [F(1) + " tabletop and legs present but the assembly is disproportionate", F(120) + " top slab floats far above the short legs"]),
            "physical_plausibility": (24, 0.9, [F(1) + ", " + F(120) + " tabletop disconnected from its legs; structure cannot stand"]),
            "camera_coverage": (76, 0.85, [F(120) + " pan keeps the table in frame"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (40, 0.8, [F(120) + " subject static but structurally broken"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (58, 0.85, [F(120) + " parts readable, proportions wrong"]),
            "appearance_detail": (35, 0.8, [F(120) + " untextured slabs"]),
            "physical_realism": (26, 0.9, [F(1) + " disconnected top violates support"]),
            "spatial_consistency": (58, 0.8, [F(120) + " parts stable but misaligned"]),
            "motion_naturalness": (66, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (38, 0.8, [F(120) + " broken proportions dominate"]),
        }),
        "visible_evidence": [F(1) + " tabletop floats high above four short legs on the stage", F(120) + " pan-left keeps the broken assembly in frame"],
        "weaknesses": ["table proportions wrong: tabletop far above legs, no contact"],
        "confidence": 0.8,
    },
    "vbench2-train-01-09": {
        "scores": {"prompt_compliance": 62, "physical_plausibility": 78, "camera_coverage": 50, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 84, "visual_clarity": 55, "appearance_detail": 40, "physical_realism": 56, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 50},
        "event_scores": {"observe_01": 60},
        "dimension_evidence": dims({
            "prompt_compliance": (62, 0.8, [F(120) + " facade with arches and tower readable"]),
            "physical_plausibility": (78, 0.85, [F(120) + " facade seated on the raised stage"]),
            "camera_coverage": (50, 0.85, [F(1) + " close start crop"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(120) + " pull-back executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous dolly out"]),
            "visual_clarity": (55, 0.85, [F(1) + " start unreadable", F(120) + " end readable"]),
            "appearance_detail": (40, 0.8, [F(120) + " plain arch tori, flat wall"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded on stage"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth pull-back"]),
            "visual_presentation": (50, 0.8, [F(120) + " end frame acceptable"]),
        }),
        "visible_evidence": [F(120) + " full facade on its raised stage after zoom-out"],
        "weaknesses": ["start crop unreadable", "flat ornament"],
        "confidence": 0.75,
    },
    "vbench2-train-01-10": {
        "scores": {"prompt_compliance": 64, "physical_plausibility": 78, "camera_coverage": 62, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 80, "visual_clarity": 60, "appearance_detail": 40, "physical_realism": 56, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 50},
        "event_scores": {"observe_01": 62},
        "dimension_evidence": dims({
            "prompt_compliance": (64, 0.8, [F(120) + " facade visible after pan-right"]),
            "physical_plausibility": (78, 0.85, [F(120) + " facade on raised stage"]),
            "camera_coverage": (62, 0.85, [F(69) + " subject near-center-left; improved from edge-pinned"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " pan-right executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (60, 0.85, [F(69) + " readable"]),
            "appearance_detail": (40, 0.8, [F(120) + " flat primitive facade"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (50, 0.8, [F(69) + " acceptable composition"]),
        }),
        "visible_evidence": [F(69) + " facade near frame after pan-right (improved framing)"],
        "weaknesses": ["flat ornament and palette"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-11": {
        "scores": {"prompt_compliance": 80, "physical_plausibility": 82, "camera_coverage": 80, "camera_innovation": 76, "character_trajectory": 50, "object_trajectory": 76, "event_timing": 72, "temporal_smoothness": 84, "visual_clarity": 78, "appearance_detail": 42, "physical_realism": 60, "spatial_consistency": 80, "motion_naturalness": 70, "visual_presentation": 66},
        "event_scores": {"observe_01": 76},
        "dimension_evidence": dims({
            "prompt_compliance": (80, 0.85, [F(120) + " vase with lip and pedestal centered on its raised stage"]),
            "physical_plausibility": (82, 0.85, [F(120) + " vase grounded on the pedestal slab (hover fixed)"]),
            "camera_coverage": (80, 0.85, [F(120) + " subject framed"]),
            "camera_innovation": (76, 0.9, [F(1) + " vs " + F(120) + " tilt-down descend executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (76, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous descend"]),
            "visual_clarity": (78, 0.85, [F(120) + " silhouette and pedestal readable"]),
            "appearance_detail": (42, 0.8, [F(120) + " smooth primitive ceramic"]),
            "physical_realism": (60, 0.8, [F(120) + " grounded contact"]),
            "spatial_consistency": (80, 0.85, [F(1) + " vs " + F(120) + " stage stable"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth descend"]),
            "visual_presentation": (66, 0.8, [F(120) + " balanced close composition"]),
        }),
        "visible_evidence": [F(120) + " vase grounded on its pedestal slab, tilt-down lands close"],
        "weaknesses": ["untextured ceramic"],
        "confidence": 0.8,
    },
    "vbench2-dev-01-12": {
        "scores": {"prompt_compliance": 58, "physical_plausibility": 78, "camera_coverage": 40, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 72, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 44, "appearance_detail": 40, "physical_realism": 56, "spatial_consistency": 76, "motion_naturalness": 68, "visual_presentation": 42},
        "event_scores": {"observe_01": 54},
        "dimension_evidence": dims({
            "prompt_compliance": (58, 0.8, [F(120) + " vase visible at orbit end"]),
            "physical_plausibility": (78, 0.85, [F(120) + " grounded vase on raised stage"]),
            "camera_coverage": (40, 0.85, [F(69) + " vase mostly outside the right edge mid-orbit"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(69) + " vs " + F(120) + " clockwise orbit executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (72, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous arc"]),
            "visual_clarity": (44, 0.85, [F(69) + " subject marginal"]),
            "appearance_detail": (40, 0.8, [F(120) + " primitive ceramic"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded"]),
            "spatial_consistency": (76, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth arc"]),
            "visual_presentation": (42, 0.8, [F(69) + " mid-orbit composition drops the subject"]),
        }),
        "visible_evidence": [F(69) + " vase mostly outside the frame mid-orbit", F(120) + " orbit re-frames the vase"],
        "weaknesses": ["orbit mid-phase keeps the subject at/beyond the frame edge"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-13": {
        "scores": {"prompt_compliance": 48, "physical_plausibility": 62, "camera_coverage": 52, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 55, "event_timing": 66, "temporal_smoothness": 80, "visual_clarity": 50, "appearance_detail": 35, "physical_realism": 50, "spatial_consistency": 62, "motion_naturalness": 66, "visual_presentation": 42},
        "event_scores": {"observe_01": 50},
        "dimension_evidence": dims({
            "prompt_compliance": (48, 0.8, [F(1) + " mid-tiers visible; the spire stays cropped so the landmark identity is weak"]),
            "physical_plausibility": (62, 0.85, [F(1) + " tower base now seated on the raised stage (hover fixed)", F(120) + " no floating gap"]),
            "camera_coverage": (52, 0.85, [F(1) + ", " + F(120) + " tower top cropped by vertical framing"]),
            "camera_innovation": (70, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (55, 0.8, [F(120) + " subject static and supported"]),
            "event_timing": (66, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (50, 0.85, [F(1) + " crop hides identity"]),
            "appearance_detail": (35, 0.8, [F(120) + " untextured tiers"]),
            "physical_realism": (50, 0.85, [F(1) + " supported base, flat light"]),
            "spatial_consistency": (62, 0.85, [F(120) + " tower stable on stage"]),
            "motion_naturalness": (66, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (42, 0.8, [F(120) + " crop loses the spire"]),
        }),
        "visible_evidence": [F(1) + " tower seated on the raised stage; spire cropped above", F(120) + " pan-left holds the cropped tower in frame"],
        "weaknesses": ["vertical framing crops the spire; landmark identity weak"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-14": {
        "scores": {"prompt_compliance": 66, "physical_plausibility": 78, "camera_coverage": 62, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 73, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 60, "appearance_detail": 38, "physical_realism": 54, "spatial_consistency": 76, "motion_naturalness": 66, "visual_presentation": 52},
        "event_scores": {"observe_01": 64},
        "dimension_evidence": dims({
            "prompt_compliance": (66, 0.85, [F(120) + " terraced cone with citadel readable after tilt-up (improved)"]),
            "physical_plausibility": (78, 0.85, [F(120) + " grounded terraces"]),
            "camera_coverage": (62, 0.85, [F(120) + " subject framed"]),
            "camera_innovation": (70, 0.9, [F(1) + " vs " + F(120) + " rise per tilt-up cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (73, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous rise"]),
            "visual_clarity": (60, 0.85, [F(120) + " terraces readable"]),
            "appearance_detail": (38, 0.8, [F(120) + " primitive terraces"]),
            "physical_realism": (54, 0.8, [F(120) + " plausible mass"]),
            "spatial_consistency": (76, 0.85, [F(120) + " stage stable"]),
            "motion_naturalness": (66, 0.8, [F(69) + " steady rise"]),
            "visual_presentation": (52, 0.8, [F(120) + " acceptable framing"]),
        }),
        "visible_evidence": [F(120) + " tilt-up ends with the terraced mountain framed"],
        "weaknesses": ["primitive surfaces"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-15": {
        "scores": {"prompt_compliance": 72, "physical_plausibility": 80, "camera_coverage": 82, "camera_innovation": 60, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 78, "visual_clarity": 70, "appearance_detail": 38, "physical_realism": 56, "spatial_consistency": 78, "motion_naturalness": 66, "visual_presentation": 58},
        "event_scores": {"observe_01": 70},
        "dimension_evidence": dims({
            "prompt_compliance": (72, 0.85, [F(120) + " terraced citadel static and readable"]),
            "physical_plausibility": (80, 0.85, [F(120) + " grounded on stage"]),
            "camera_coverage": (82, 0.85, [F(120) + " fixed framing keeps the subject"]),
            "camera_innovation": (60, 0.85, [F(120) + " static per cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (78, 0.85, [F(120) + " no motion artifacts"]),
            "visual_clarity": (70, 0.85, [F(120) + " terraces readable"]),
            "appearance_detail": (38, 0.8, [F(120) + " primitive surfaces"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (66, 0.8, [F(120) + " no motion"]),
            "visual_presentation": (58, 0.8, [F(120) + " stable composition"]),
        }),
        "visible_evidence": [F(120) + " static shot holds the terraced citadel"],
        "weaknesses": ["primitive surfaces"],
        "confidence": 0.78,
    },
    "vbench2-dev-01-16": {
        "scores": {"prompt_compliance": 58, "physical_plausibility": 66, "camera_coverage": 74, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 56, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 62, "appearance_detail": 38, "physical_realism": 48, "spatial_consistency": 66, "motion_naturalness": 66, "visual_presentation": 44},
        "event_scores": {"observe_01": 58},
        "dimension_evidence": dims({
            "prompt_compliance": (58, 0.85, [F(120) + " tiered palace with gate, columns, roofs readable"]),
            "physical_plausibility": (66, 0.85, [F(120) + " palace seated on the raised stage (hover fixed)"]),
            "camera_coverage": (74, 0.85, [F(120) + " pan keeps the palace framed"]),
            "camera_innovation": (70, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (56, 0.8, [F(120) + " subject static and supported"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (62, 0.85, [F(120) + " structure readable"]),
            "appearance_detail": (38, 0.8, [F(120) + " flat slabs, no ornament"]),
            "physical_realism": (48, 0.85, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (66, 0.85, [F(120) + " stable on stage"]),
            "motion_naturalness": (66, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (44, 0.8, [F(120) + " muted palette"]),
        }),
        "visible_evidence": [F(120) + " palace grounded on its raised stage during pan-left"],
        "weaknesses": ["no ornament detail; flat palette"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-17": {
        "scores": {"prompt_compliance": 52, "physical_plausibility": 60, "camera_coverage": 46, "camera_innovation": 60, "character_trajectory": 50, "object_trajectory": 55, "event_timing": 55, "temporal_smoothness": 70, "visual_clarity": 42, "appearance_detail": 32, "physical_realism": 45, "spatial_consistency": 52, "motion_naturalness": 60, "visual_presentation": 38},
        "event_scores": {"observe_01": 50},
        "dimension_evidence": dims({
            "prompt_compliance": (52, 0.8, [F(1) + " palace visible from a low first-person approach", F(120) + " ends close on the gate wall (improved from ending inside geometry)"]),
            "physical_plausibility": (60, 0.85, [F(120) + " camera stops outside the facade; no penetration"]),
            "camera_coverage": (46, 0.85, [F(120) + " final crop shows only the gate"]),
            "camera_innovation": (60, 0.85, [F(1) + " vs " + F(120) + " airborne dolly-in executed but ends too close"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (55, 0.8, [F(120) + " subject static and supported"]),
            "event_timing": (55, 0.8, [F(120) + " approach staged across the clip"]),
            "temporal_smoothness": (70, 0.85, [F(69) + " continuous flight"]),
            "visual_clarity": (42, 0.85, [F(120) + " close crop limits readability"]),
            "appearance_detail": (32, 0.8, [F(120) + " flat walls"]),
            "physical_realism": (45, 0.85, [F(1) + " grounded palace"]),
            "spatial_consistency": (52, 0.8, [F(1) + " vs " + F(120) + " scale readable at start"]),
            "motion_naturalness": (60, 0.85, [F(69) + " smooth flight"]),
            "visual_presentation": (38, 0.8, [F(120) + " end crop too tight"]),
        }),
        "visible_evidence": [F(1) + " low first-person view of the palace", F(120) + " dolly ends just outside the gate wall (no collision)"],
        "weaknesses": ["final framing too tight on the gate wall"],
        "confidence": 0.7,
    },
    "vbench2-dev-01-18": {
        "scores": {"prompt_compliance": 74, "physical_plausibility": 80, "camera_coverage": 76, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 70, "temporal_smoothness": 82, "visual_clarity": 70, "appearance_detail": 42, "physical_realism": 58, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 58},
        "event_scores": {"observe_01": 72},
        "dimension_evidence": dims({
            "prompt_compliance": (74, 0.85, [F(120) + " open laptop with base, tilted screen and key rows"]),
            "physical_plausibility": (80, 0.85, [F(120) + " laptop seated on the raised stage (radius fix confirmed)"]),
            "camera_coverage": (76, 0.85, [F(120) + " pan keeps the laptop framed"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " pan-right executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (82, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (70, 0.85, [F(120) + " keyboard rows readable"]),
            "appearance_detail": (42, 0.8, [F(120) + " untextured shell, glow panel subtle"]),
            "physical_realism": (58, 0.85, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (58, 0.8, [F(120) + " acceptable composition"]),
        }),
        "visible_evidence": [F(120) + " laptop grounded on its stage during pan-right"],
        "weaknesses": ["muted materials"],
        "confidence": 0.78,
    },
    "vbench2-dev-01-19": {
        "scores": {"prompt_compliance": 66, "physical_plausibility": 78, "camera_coverage": 74, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 82, "visual_clarity": 60, "appearance_detail": 38, "physical_realism": 56, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 54},
        "event_scores": {"observe_01": 64},
        "dimension_evidence": dims({
            "prompt_compliance": (66, 0.85, [F(120) + " watch with bezel ring and strap on the raised stage"]),
            "physical_plausibility": (78, 0.85, [F(120) + " watch seated on its stage (radius fix confirmed)"]),
            "camera_coverage": (74, 0.85, [F(120) + " zoom-out keeps the watch framed"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " pull-back executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (82, 0.85, [F(69) + " continuous pull-back"]),
            "visual_clarity": (60, 0.85, [F(120) + " dial details small at this scale"]),
            "appearance_detail": (38, 0.8, [F(120) + " dial and hands minimal"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth dolly"]),
            "visual_presentation": (54, 0.8, [F(120) + " plaque-like staging reads generic"]),
        }),
        "visible_evidence": [F(120) + " watch grounded on its stage after zoom-out"],
        "weaknesses": ["dial detail small; staging reads generic"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-20": {
        "scores": {"prompt_compliance": 56, "physical_plausibility": 78, "camera_coverage": 42, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 72, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 44, "appearance_detail": 38, "physical_realism": 56, "spatial_consistency": 76, "motion_naturalness": 68, "visual_presentation": 42},
        "event_scores": {"observe_01": 54},
        "dimension_evidence": dims({
            "prompt_compliance": (56, 0.8, [F(120) + " watch visible at orbit end"]),
            "physical_plausibility": (78, 0.85, [F(120) + " grounded watch"]),
            "camera_coverage": (42, 0.85, [F(69) + " watch at the right edge, mostly outside the frame mid-orbit"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(69) + " vs " + F(120) + " clockwise orbit executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (72, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous arc"]),
            "visual_clarity": (44, 0.85, [F(69) + " subject marginal"]),
            "appearance_detail": (38, 0.8, [F(120) + " minimal dial detail"]),
            "physical_realism": (56, 0.8, [F(120) + " grounded"]),
            "spatial_consistency": (76, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth arc"]),
            "visual_presentation": (42, 0.8, [F(69) + " mid-orbit composition loses the subject"]),
        }),
        "visible_evidence": [F(69) + " watch mostly outside the frame mid-orbit", F(120) + " orbit re-frames the watch"],
        "weaknesses": ["orbit mid-phase framing drops the subject"],
        "confidence": 0.75,
    },
}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for case_id, payload in REVIEW_CASES.items():
        scores = {
            **payload["scores"],
            "event_scores": payload.get("event_scores"),
            "dimension_evidence": payload.get("dimension_evidence"),
            "visible_evidence": payload["visible_evidence"],
            "weaknesses": payload["weaknesses"],
            "confidence": payload["confidence"],
        }
        target = OUT / f"{case_id}-scores.json"
        target.write_text(json.dumps({"scores": scores}, ensure_ascii=False, indent=1), encoding="utf-8")
    print(json.dumps({"written": len(REVIEW_CASES)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
