"""Authored round-1 attempt-1 assistant reviews (15 rendered cases).

All scores, evidence references, and weaknesses below were authored by the
driving glm-5.3-flash session after inspecting the sampled frames of each
case (frames 0001/0035/0069/0120 of the real proxy.mp4).
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("out/assistant-session/reviews/round1-attempt1")


def F(n: int) -> str:
    return f"frame_{n:04d}.png"


def dims(table: dict) -> dict:
    return {
        name: {"confidence": conf, "evidence_completeness": 1.0, "evidence_refs": refs}
        for name, (score, conf, refs) in table.items()
    }


NO_CHARACTER = "no character is present in the prompt or frames"

REVIEW_CASES: dict[str, dict] = {
    "vbench2-train-01-01": {
        "scores": {"prompt_compliance": 70, "physical_plausibility": 80, "camera_coverage": 55, "camera_innovation": 78, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 70, "temporal_smoothness": 85, "visual_clarity": 50, "appearance_detail": 40, "physical_realism": 55, "spatial_consistency": 80, "motion_naturalness": 70, "visual_presentation": 48},
        "event_scores": {"observe_01": 72},
        "dimension_evidence": dims({
            "prompt_compliance": (70, 0.8, [F(1) + " garden mound fills frame, composition unreadable", F(120) + " full garden: mound, three tree crowns, platform, path"]),
            "physical_plausibility": (80, 0.85, [F(120) + " all parts supported on the stage slab"]),
            "camera_coverage": (55, 0.8, [F(1) + " over-cropped start loses the subject", F(120) + " subject framed after the pull back"]),
            "camera_innovation": (78, 0.9, [F(1) + " vs " + F(120) + " continuous dolly outward per zoom-out cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.85, [F(1), F(120) + " subject holds its planned position"]),
            "event_timing": (70, 0.85, [F(120) + " observe event staged for the full clip"]),
            "temporal_smoothness": (85, 0.9, [F(18), F(69), F(120) + " continuous pull-back without jumps"]),
            "visual_clarity": (50, 0.85, [F(1) + " start frame is an unreadable close blob", F(120) + " end frame readable"]),
            "appearance_detail": (40, 0.85, [F(120) + " bare primitives, flat untextured shading"]),
            "physical_realism": (55, 0.8, [F(120) + " plausible support, no contact shadows under flat light"]),
            "spatial_consistency": (80, 0.85, [F(1) + " vs " + F(120) + " platform and ground stable"]),
            "motion_naturalness": (70, 0.8, [F(69) + " steady camera motion, no subject motion expected"]),
            "visual_presentation": (48, 0.8, [F(1) + " crop fails", F(120) + " decent end composition, monotone gray palette"]),
        }),
        "visible_evidence": [F(1) + " garden mound overfills the frame", F(120) + " garden diorama fully framed: mound, tree crowns, trunk, platform"],
        "weaknesses": ["start framing is far too close; the subject is unreadable until late frames", "washed-out near-white palette hides surface detail"],
        "confidence": 0.78,
    },
    "vbench2-train-01-02": {
        "scores": {"prompt_compliance": 62, "physical_plausibility": 80, "camera_coverage": 35, "camera_innovation": 75, "character_trajectory": 50, "object_trajectory": 72, "event_timing": 70, "temporal_smoothness": 80, "visual_clarity": 40, "appearance_detail": 38, "physical_realism": 55, "spatial_consistency": 78, "motion_naturalness": 70, "visual_presentation": 40},
        "event_scores": {"observe_01": 55},
        "dimension_evidence": dims({
            "prompt_compliance": (62, 0.8, [F(1) + " garden present", F(120) + " garden back in frame after orbit"]),
            "physical_plausibility": (80, 0.85, [F(120) + " scene supported and stable"]),
            "camera_coverage": (35, 0.85, [F(69) + " subject drifts to the right edge; most of the frame is empty floor"]),
            "camera_innovation": (75, 0.9, [F(1) + " vs " + F(69) + " vs " + F(120) + " full clockwise orbit executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (72, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous arc, no jumps"]),
            "visual_clarity": (40, 0.85, [F(69) + " subject barely readable at frame edge"]),
            "appearance_detail": (38, 0.8, [F(120) + " primitive shapes, washed shading"]),
            "physical_realism": (55, 0.8, [F(120) + " plausible staging, flat light"]),
            "spatial_consistency": (78, 0.85, [F(1) + " vs " + F(120) + " layout stable"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth camera arc"]),
            "visual_presentation": (40, 0.8, [F(69) + " composition loses the subject mid-shot"]),
        }),
        "visible_evidence": [F(1) + " garden at orbit start", F(69) + " garden exits to the right edge", F(120) + " orbit completes with the garden re-framed"],
        "weaknesses": ["mid-orbit framing drops the subject to the frame edge", "washed-out palette"],
        "confidence": 0.75,
    },
    "vbench2-train-01-03": {
        "scores": {"prompt_compliance": 78, "physical_plausibility": 82, "camera_coverage": 82, "camera_innovation": 76, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 72, "temporal_smoothness": 84, "visual_clarity": 75, "appearance_detail": 42, "physical_realism": 58, "spatial_consistency": 82, "motion_naturalness": 70, "visual_presentation": 62},
        "event_scores": {"observe_01": 75},
        "dimension_evidence": dims({
            "prompt_compliance": (78, 0.85, [F(1) + " stepped pyramid centered", F(120) + " courses and capstone readable after tilt"]),
            "physical_plausibility": (82, 0.85, [F(120) + " pyramid rests on the stage"]),
            "camera_coverage": (82, 0.85, [F(1) + ", " + F(120) + " subject stays framed"]),
            "camera_innovation": (76, 0.9, [F(1) + " vs " + F(120) + " camera lowers toward the subject per tilt-down cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(18), F(120) + " continuous descend"]),
            "visual_clarity": (75, 0.85, [F(120) + " stepped courses clearly readable"]),
            "appearance_detail": (42, 0.8, [F(120) + " flat facets, no stone texture"]),
            "physical_realism": (58, 0.8, [F(120) + " grounded contact, weak shadowing"]),
            "spatial_consistency": (82, 0.85, [F(1) + " vs " + F(120) + " platform stable"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth camera descend"]),
            "visual_presentation": (62, 0.8, [F(1) + " good composition", F(120) + " closer crop still balanced"]),
        }),
        "visible_evidence": [F(1) + " stepped pyramid well framed", F(120) + " tilt-down lands closer with courses and capstone readable"],
        "weaknesses": ["surfaces are untextured primitives under flat light"],
        "confidence": 0.8,
    },
    "vbench2-train-01-04": {
        "scores": {"prompt_compliance": 55, "physical_plausibility": 80, "camera_coverage": 40, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 82, "visual_clarity": 45, "appearance_detail": 38, "physical_realism": 55, "spatial_consistency": 75, "motion_naturalness": 68, "visual_presentation": 42},
        "event_scores": {"observe_01": 55},
        "dimension_evidence": dims({
            "prompt_compliance": (55, 0.8, [F(1) + " mountain cone visible", F(120) + " only the slope fills the frame; subject unidentifiable"]),
            "physical_plausibility": (80, 0.85, [F(1) + " grounded cone"]),
            "camera_coverage": (40, 0.85, [F(120) + " zoom-in overshoots; subject unreadable"]),
            "camera_innovation": (70, 0.85, [F(1) + " vs " + F(120) + " dolly-in executed per cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(1) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (82, 0.85, [F(69) + " continuous push in"]),
            "visual_clarity": (45, 0.85, [F(120) + " end frame is a featureless slope"]),
            "appearance_detail": (38, 0.8, [F(1) + " primitive cone, snow cap barely distinct"]),
            "physical_realism": (55, 0.8, [F(1) + " plausible mass, flat light"]),
            "spatial_consistency": (75, 0.8, [F(1) + " vs " + F(120) + " stage stable"]),
            "motion_naturalness": (68, 0.8, [F(69) + " steady dolly"]),
            "visual_presentation": (42, 0.8, [F(120) + " end crop discards the landmark silhouette"]),
        }),
        "visible_evidence": [F(1) + " mountain cone framed", F(120) + " zoom-in ends over-cropped on the slope"],
        "weaknesses": ["zoom-in overshoots until only a featureless slope is visible"],
        "confidence": 0.75,
    },
    "vbench2-train-01-05": {
        "scores": {"prompt_compliance": 78, "physical_plausibility": 82, "camera_coverage": 80, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 72, "temporal_smoothness": 84, "visual_clarity": 76, "appearance_detail": 40, "physical_realism": 56, "spatial_consistency": 80, "motion_naturalness": 70, "visual_presentation": 62},
        "event_scores": {"observe_01": 75},
        "dimension_evidence": dims({
            "prompt_compliance": (78, 0.85, [F(1) + ", " + F(120) + " cone stays framed while sliding left per pan cue"]),
            "physical_plausibility": (82, 0.85, [F(1) + " grounded subject"]),
            "camera_coverage": (80, 0.85, [F(120) + " subject fully visible at pan end"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous lateral glide"]),
            "visual_clarity": (76, 0.85, [F(120) + " silhouette readable"]),
            "appearance_detail": (40, 0.8, [F(120) + " untextured primitive surfaces"]),
            "physical_realism": (56, 0.8, [F(1) + " plausible staging, weak shadows"]),
            "spatial_consistency": (80, 0.85, [F(1) + " vs " + F(120) + " stable layout"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (62, 0.8, [F(120) + " balanced off-center composition"]),
        }),
        "visible_evidence": [F(1) + " mountain framed", F(120) + " pan-left ends with the mountain fully framed"],
        "weaknesses": ["flat lighting and untextured surfaces"],
        "confidence": 0.8,
    },
    "vbench2-train-01-06": {
        "scores": {"prompt_compliance": 68, "physical_plausibility": 78, "camera_coverage": 78, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 82, "visual_clarity": 68, "appearance_detail": 40, "physical_realism": 54, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 58},
        "event_scores": {"observe_01": 68},
        "dimension_evidence": dims({
            "prompt_compliance": (68, 0.8, [F(1) + " lagoon water disc with shore ring and palm", F(120) + " tilt-up reveals the disc from above"]),
            "physical_plausibility": (78, 0.85, [F(120) + " water disc rests on the stage; palm planted"]),
            "camera_coverage": (78, 0.85, [F(1) + ", " + F(120) + " lagoon stays framed"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " camera rises per tilt-up cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (82, 0.85, [F(69) + " continuous rise"]),
            "visual_clarity": (68, 0.85, [F(120) + " ring and palm readable, water reads flat"]),
            "appearance_detail": (40, 0.8, [F(120) + " no water ripple or translucency"]),
            "physical_realism": (54, 0.8, [F(1) + " water surface is a solid flat disc"]),
            "spatial_consistency": (78, 0.85, [F(1) + " vs " + F(120) + " layout stable"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth rise"]),
            "visual_presentation": (58, 0.8, [F(120) + " acceptable composition, muted palette"]),
        }),
        "visible_evidence": [F(1) + " lagoon close view", F(120) + " tilt-up reveals the full disc and palm"],
        "weaknesses": ["water renders as a flat opaque disc without ripples"],
        "confidence": 0.75,
    },
    "vbench2-train-01-08": {
        "scores": {"prompt_compliance": 45, "physical_plausibility": 20, "camera_coverage": 78, "camera_innovation": 72, "character_trajectory": 50, "object_trajectory": 40, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 60, "appearance_detail": 35, "physical_realism": 24, "spatial_consistency": 60, "motion_naturalness": 66, "visual_presentation": 40},
        "event_scores": {"observe_01": 55},
        "dimension_evidence": dims({
            "prompt_compliance": (45, 0.85, [F(1) + " tabletop with legs present but the assembly is broken", F(120) + " legs hang disconnected mid-air"]),
            "physical_plausibility": (20, 0.9, [F(1) + ", " + F(120) + " legs float detached below the tabletop; no contact with the stage"]),
            "camera_coverage": (78, 0.85, [F(120) + " pan keeps the table in frame"]),
            "camera_innovation": (72, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (40, 0.8, [F(120) + " subject static but structurally broken"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (60, 0.85, [F(120) + " parts readable, relations wrong"]),
            "appearance_detail": (35, 0.8, [F(120) + " untextured slabs and cylinders"]),
            "physical_realism": (24, 0.9, [F(1) + " floating disconnected legs violate support"]),
            "spatial_consistency": (60, 0.8, [F(1) + " vs " + F(120) + " parts stable but misaligned"]),
            "motion_naturalness": (66, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (40, 0.8, [F(120) + " broken assembly dominates the impression"]),
        }),
        "visible_evidence": [F(1) + " table floats above the stage with four detached legs", F(120) + " pan-left keeps the broken assembly in frame"],
        "weaknesses": ["table legs are disconnected and hover mid-air - hard physical violation"],
        "confidence": 0.8,
    },
    "vbench2-train-01-09": {
        "scores": {"prompt_compliance": 60, "physical_plausibility": 78, "camera_coverage": 48, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 74, "event_timing": 70, "temporal_smoothness": 84, "visual_clarity": 55, "appearance_detail": 40, "physical_realism": 55, "spatial_consistency": 78, "motion_naturalness": 68, "visual_presentation": 50},
        "event_scores": {"observe_01": 60},
        "dimension_evidence": dims({
            "prompt_compliance": (60, 0.8, [F(120) + " facade with three arches and tower readable", F(1) + " start crop unreadable"]),
            "physical_plausibility": (78, 0.85, [F(120) + " facade grounded on stage"]),
            "camera_coverage": (48, 0.85, [F(1) + " extreme close-up loses the subject"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(120) + " pull-back executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (74, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (70, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous dolly out"]),
            "visual_clarity": (55, 0.85, [F(1) + " unreadable crop", F(120) + " end readable"]),
            "appearance_detail": (40, 0.8, [F(120) + " flat wall, arches as plain tori"]),
            "physical_realism": (55, 0.8, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (78, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth pull-back"]),
            "visual_presentation": (50, 0.8, [F(1) + " crop fails", F(120) + " decent end frame"]),
        }),
        "visible_evidence": [F(1) + " arches overfill the frame", F(120) + " full facade: wall, three arches, watch tower"],
        "weaknesses": ["start framing too close to identify the subject"],
        "confidence": 0.75,
    },
    "vbench2-train-01-10": {
        "scores": {"prompt_compliance": 60, "physical_plausibility": 78, "camera_coverage": 52, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 73, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 55, "appearance_detail": 40, "physical_realism": 55, "spatial_consistency": 76, "motion_naturalness": 68, "visual_presentation": 45},
        "event_scores": {"observe_01": 58},
        "dimension_evidence": dims({
            "prompt_compliance": (60, 0.8, [F(120) + " facade visible at the left edge after pan"]),
            "physical_plausibility": (78, 0.85, [F(120) + " grounded facade"]),
            "camera_coverage": (52, 0.85, [F(69) + " subject pinned to the left edge; large empty floor right"]),
            "camera_innovation": (70, 0.9, [F(1) + " vs " + F(120) + " pan-right executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (73, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (55, 0.85, [F(69) + " edge framing hurts readability"]),
            "appearance_detail": (40, 0.8, [F(120) + " flat primitive facade"]),
            "physical_realism": (55, 0.8, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (76, 0.8, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (45, 0.8, [F(69) + " composition drifts the subject off-center"]),
        }),
        "visible_evidence": [F(69) + " facade at the left edge with empty floor right", F(120) + " pan completes with the subject still edge-framed"],
        "weaknesses": ["pan-right leaves the subject pinned to the frame edge"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-11": {
        "scores": {"prompt_compliance": 78, "physical_plausibility": 80, "camera_coverage": 80, "camera_innovation": 75, "character_trajectory": 50, "object_trajectory": 75, "event_timing": 72, "temporal_smoothness": 84, "visual_clarity": 76, "appearance_detail": 42, "physical_realism": 58, "spatial_consistency": 80, "motion_naturalness": 70, "visual_presentation": 65},
        "event_scores": {"observe_01": 75},
        "dimension_evidence": dims({
            "prompt_compliance": (78, 0.85, [F(1) + " vase with lip and pedestal centered", F(120) + " closer view keeps all parts readable"]),
            "physical_plausibility": (80, 0.85, [F(1) + " vase grounded on its pedestal"]),
            "camera_coverage": (80, 0.85, [F(1) + ", " + F(120) + " subject framed"]),
            "camera_innovation": (75, 0.9, [F(1) + " vs " + F(120) + " descend per tilt-down cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (75, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (72, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (84, 0.85, [F(69) + " continuous descend"]),
            "visual_clarity": (76, 0.85, [F(120) + " silhouette and pedestal readable"]),
            "appearance_detail": (42, 0.8, [F(120) + " smooth primitive ceramic, no texture"]),
            "physical_realism": (58, 0.8, [F(1) + " grounded contact, flat light"]),
            "spatial_consistency": (80, 0.85, [F(1) + " vs " + F(120) + " stage stable"]),
            "motion_naturalness": (70, 0.8, [F(69) + " smooth descend"]),
            "visual_presentation": (65, 0.8, [F(120) + " balanced close composition"]),
        }),
        "visible_evidence": [F(1) + " vase composed on the stage", F(120) + " tilt-down ends closer with the vase fully readable"],
        "weaknesses": ["untextured surfaces under flat light"],
        "confidence": 0.8,
    },
    "vbench2-dev-01-12": {
        "scores": {"prompt_compliance": 60, "physical_plausibility": 78, "camera_coverage": 38, "camera_innovation": 74, "character_trajectory": 50, "object_trajectory": 72, "event_timing": 68, "temporal_smoothness": 80, "visual_clarity": 45, "appearance_detail": 40, "physical_realism": 55, "spatial_consistency": 76, "motion_naturalness": 68, "visual_presentation": 40},
        "event_scores": {"observe_01": 55},
        "dimension_evidence": dims({
            "prompt_compliance": (60, 0.8, [F(120) + " vase back in frame at orbit end"]),
            "physical_plausibility": (78, 0.85, [F(120) + " grounded vase"]),
            "camera_coverage": (38, 0.85, [F(69) + " vase pushed to the far right edge; frame mostly empty floor"]),
            "camera_innovation": (74, 0.9, [F(1) + " vs " + F(69) + " vs " + F(120) + " clockwise orbit executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (72, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (68, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous arc"]),
            "visual_clarity": (45, 0.85, [F(69) + " subject barely visible"]),
            "appearance_detail": (40, 0.8, [F(120) + " primitive ceramic"]),
            "physical_realism": (55, 0.8, [F(120) + " grounded, flat light"]),
            "spatial_consistency": (76, 0.85, [F(120) + " stable layout"]),
            "motion_naturalness": (68, 0.8, [F(69) + " smooth arc"]),
            "visual_presentation": (40, 0.8, [F(69) + " mid-orbit composition loses the subject"]),
        }),
        "visible_evidence": [F(69) + " vase at the right edge, frame mostly empty", F(120) + " orbit completes and re-frames the vase"],
        "weaknesses": ["mid-orbit framing drops the subject"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-13": {
        "scores": {"prompt_compliance": 40, "physical_plausibility": 22, "camera_coverage": 50, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 45, "event_timing": 65, "temporal_smoothness": 80, "visual_clarity": 45, "appearance_detail": 35, "physical_realism": 25, "spatial_consistency": 55, "motion_naturalness": 66, "visual_presentation": 38},
        "event_scores": {"observe_01": 45},
        "dimension_evidence": dims({
            "prompt_compliance": (40, 0.8, [F(1) + " only the middle tiers visible; the spire is cropped and the landmark reads as a plain tube"]),
            "physical_plausibility": (22, 0.9, [F(1) + ", " + F(120) + " the tower base hovers above the stage with a visible gap"]),
            "camera_coverage": (50, 0.85, [F(120) + " top of the tower stays out of frame"]),
            "camera_innovation": (70, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (45, 0.8, [F(120) + " subject static but floating"]),
            "event_timing": (65, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (45, 0.85, [F(1) + " crop hides the landmark identity"]),
            "appearance_detail": (35, 0.8, [F(120) + " untextured tiers"]),
            "physical_realism": (25, 0.9, [F(1) + " floating building violates support"]),
            "spatial_consistency": (55, 0.8, [F(120) + " tower stable but detached from the stage"]),
            "motion_naturalness": (66, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (38, 0.8, [F(120) + " crop and gap dominate"]),
        }),
        "visible_evidence": [F(1) + " tower tiers visible, spire cropped, base floating above the stage", F(120) + " pan-left keeps the floating, cropped tower in frame"],
        "weaknesses": ["tower base hovers above the platform - support violation", "vertical framing crops the spire"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-14": {
        "scores": {"prompt_compliance": 55, "physical_plausibility": 76, "camera_coverage": 45, "camera_innovation": 68, "character_trajectory": 50, "object_trajectory": 72, "event_timing": 66, "temporal_smoothness": 78, "visual_clarity": 42, "appearance_detail": 38, "physical_realism": 52, "spatial_consistency": 72, "motion_naturalness": 64, "visual_presentation": 38},
        "event_scores": {"observe_01": 55},
        "dimension_evidence": dims({
            "prompt_compliance": (55, 0.8, [F(1) + " terraced cone with citadel block recognizable", F(120) + " tilt-up ends below the slope; only the base fills the frame"]),
            "physical_plausibility": (76, 0.85, [F(1) + " grounded terraces"]),
            "camera_coverage": (45, 0.85, [F(120) + " end frame loses the citadel"]),
            "camera_innovation": (68, 0.9, [F(1) + " vs " + F(120) + " camera rises per tilt-up cue"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (72, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (66, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (78, 0.85, [F(69) + " continuous rise"]),
            "visual_clarity": (42, 0.85, [F(120) + " end crop unreadable"]),
            "appearance_detail": (38, 0.8, [F(1) + " primitive terraces, no stone texture"]),
            "physical_realism": (52, 0.8, [F(1) + " plausible mass, flat light"]),
            "spatial_consistency": (72, 0.8, [F(1) + " vs " + F(120) + " stage stable"]),
            "motion_naturalness": (64, 0.8, [F(69) + " steady rise"]),
            "visual_presentation": (38, 0.8, [F(120) + " end framing fails"]),
        }),
        "visible_evidence": [F(1) + " terraced mountain with citadel readable", F(120) + " tilt-up ends over-cropped at the slope"],
        "weaknesses": ["tilt-up overshoots and loses the subject"],
        "confidence": 0.7,
    },
    "vbench2-dev-01-16": {
        "scores": {"prompt_compliance": 50, "physical_plausibility": 22, "camera_coverage": 75, "camera_innovation": 70, "character_trajectory": 50, "object_trajectory": 45, "event_timing": 66, "temporal_smoothness": 80, "visual_clarity": 60, "appearance_detail": 38, "physical_realism": 26, "spatial_consistency": 55, "motion_naturalness": 66, "visual_presentation": 40},
        "event_scores": {"observe_01": 50},
        "dimension_evidence": dims({
            "prompt_compliance": (50, 0.8, [F(69) + " tiered palace with gate, columns and roofs recognizable"]),
            "physical_plausibility": (22, 0.9, [F(69) + ", " + F(120) + " the whole palace hovers above the platform with a visible gap"]),
            "camera_coverage": (75, 0.85, [F(120) + " pan keeps the palace framed"]),
            "camera_innovation": (70, 0.9, [F(1) + " vs " + F(120) + " lateral pan executed"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (45, 0.8, [F(120) + " subject static but floating"]),
            "event_timing": (66, 0.8, [F(120) + " observe staged throughout"]),
            "temporal_smoothness": (80, 0.85, [F(69) + " continuous glide"]),
            "visual_clarity": (60, 0.85, [F(120) + " structure readable"]),
            "appearance_detail": (38, 0.8, [F(120) + " flat slabs, no ornament"]),
            "physical_realism": (26, 0.9, [F(69) + " floating building violates support"]),
            "spatial_consistency": (55, 0.8, [F(120) + " stable but detached from the stage"]),
            "motion_naturalness": (66, 0.8, [F(69) + " smooth pan"]),
            "visual_presentation": (40, 0.8, [F(120) + " hover gap dominates"]),
        }),
        "visible_evidence": [F(69) + " palace floats above the platform", F(120) + " pan-left keeps the floating palace framed"],
        "weaknesses": ["entire palace hovers above the stage - support violation"],
        "confidence": 0.75,
    },
    "vbench2-dev-01-17": {
        "scores": {"prompt_compliance": 30, "physical_plausibility": 25, "camera_coverage": 25, "camera_innovation": 45, "character_trajectory": 50, "object_trajectory": 45, "event_timing": 45, "temporal_smoothness": 60, "visual_clarity": 22, "appearance_detail": 30, "physical_realism": 30, "spatial_consistency": 40, "motion_naturalness": 50, "visual_presentation": 25},
        "event_scores": {"observe_01": 35},
        "dimension_evidence": dims({
            "prompt_compliance": (30, 0.8, [F(1) + " palace tiny at the right edge over empty floor", F(120) + " camera ends inside the facade; only a wall is visible"]),
            "physical_plausibility": (25, 0.9, [F(120) + " camera penetrates the building geometry"]),
            "camera_coverage": (25, 0.85, [F(1) + ", " + F(120) + " subject unreadable at both ends"]),
            "camera_innovation": (45, 0.85, [F(1) + " vs " + F(120) + " first-person airborne dolly flies but collides"]),
            "character_trajectory": (50, 0.9, [NO_CHARACTER]),
            "object_trajectory": (45, 0.8, [F(120) + " subject static per plan"]),
            "event_timing": (45, 0.8, [F(120) + " observe staging lost inside the wall"]),
            "temporal_smoothness": (60, 0.85, [F(69) + " motion continuous until the collision"]),
            "visual_clarity": (22, 0.85, [F(120) + " featureless wall fills the frame"]),
            "appearance_detail": (30, 0.8, [F(120) + " flat untextured surfaces"]),
            "physical_realism": (30, 0.8, [F(1) + " grounded palace, flat light"]),
            "spatial_consistency": (40, 0.8, [F(1) + " vs " + F(120) + " scale relations unreadable"]),
            "motion_naturalness": (50, 0.85, [F(69) + " flight path exists but ends in collision"]),
            "visual_presentation": (25, 0.85, [F(1) + " empty frame", F(120) + " wall frame"]),
        }),
        "visible_evidence": [F(1) + " palace tiny at the right edge", F(120) + " camera ends inside the facade; frame filled by a flat wall"],
        "weaknesses": ["airborne dolly flies into the building and ends inside geometry", "start framing leaves the subject unreadable"],
        "confidence": 0.7,
    },
}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for case_id, payload in REVIEW_CASES.items():
        # VLMJudgeResponse carries visible_evidence/weaknesses/confidence as
        # fields of the scores object itself.
        scores = {
            **payload["scores"],
            "event_scores": payload.get("event_scores"),
            "dimension_evidence": payload.get("dimension_evidence"),
            "visible_evidence": payload["visible_evidence"],
            "weaknesses": payload["weaknesses"],
            "confidence": payload["confidence"],
        }
        target = OUT / f"{case_id}-scores.json"
        target.write_text(json.dumps({"scores": scores}, ensure_ascii=False, indent=1), encoding="utf-8")
    print(json.dumps({"written": sorted(REVIEW_CASES)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
